@startuml
'https://plantuml.com/sequence-diagram
actor Client
participant WebsiteDestinationsPage
participant DynamoDBDestinationsActivity
database DestinationsTable
autonumber

Client -> WebsiteDestinationsPage: selects a category and number of destinations to return (1, 5, whole list) in the dropdown menu
WebsiteDestinationsPage -> DynamoDBDestinationsActivity: getDestinations(category)

DynamoDBDestinationsActivity -> DestinationsTable: get Destinations
DynamoDBDestinationsActivity <- DestinationsTable: List<Destinations>
DynamoDBDestinationsActivity -> WebsiteDestinationsPage: List<Destinations>
Client<- WebsiteDestinationsPage: List<Destinations>

@enduml