@startuml
'https://plantuml.com/sequence-diagram
actor Client
participant WebsiteFavoritesPage
participant DynamoDBFavoritesActivity
database FavoritesTable
autonumber

Client -> WebsiteFavoritesPage: requests with URL
WebsiteFavoritesPage -> DynamoDBFavoritesActivity: getFavorites()

DynamoDBFavoritesActivity -> FavoritesTable: get Favorites (UUID)
DynamoDBFavoritesActivity <- FavoritesTable: List<Favorites>
DynamoDBFavoritesActivity -> WebsiteFavoritesPage: List<Favorites>
Client<- WebsiteFavoritesPage: List<Favorites>
@enduml